[package]
rust-version.workspace = true
name = "sdkwork-routes-models-catalog-backend-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "SDKWork intelligence catalog backend API route crate with http route manifest."


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
axum.workspace = true
sdkwork_models_catalog_service.workspace = true
sdkwork_models_contract_service.workspace = true
sdkwork-models.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-iam-web-adapter.workspace = true

[dev-dependencies]
sdkwork-web-core.workspace = true
