[package]
rust-version.workspace = true
name = "sdkwork-api-models-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-models application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_models_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork_models_service_host.workspace = true
sdkwork_models_database_host.workspace = true
sdkwork_models_catalog_repository_sqlx.workspace = true
sdkwork_models_contract_service.workspace = true
sdkwork-database-id.workspace = true
sdkwork-database-sqlx.workspace = true
sqlx.workspace = true
sdkwork_routes_models_catalog_app_api = { workspace = true }
sdkwork_routes_models_catalog_backend_api = { workspace = true }
