/* This file is generated by tools/generate-mainstream-agent-model-catalog.mjs. */
import type { MainstreamAgentModelCatalogEntry } from './unifiedAgentModelCatalog';

export const SDKWORK_MODELS_CATALOG_VERSION = "2026.09.17.1";
export const SDKWORK_MODELS_CATALOG_GENERATED_AT = "2026-09-17T00:00:00Z";

export const SDKWORK_MAINSTREAM_AGENT_MODEL_CATALOG: readonly MainstreamAgentModelCatalogEntry[] = [
  {
    "catalogKey": "openai/gpt-6-astra",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1050000,
    "description": "GPT-6 Astra, OpenAI's new flagship model released on 2026-09-03, leading the GPT-6 generation with 1.05M token context for the most demanding reasoning and long-horizon agentic work.",
    "displayName": "GPT-6 Astra",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "gpt-6-astra",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1250,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-6",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context"
    ],
    "sortOrder": 0,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-sol",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1050000,
    "description": "GPT-5.6 Sol flagship model with max reasoning and ultra sub-agent modes. Generally available as of July 2026. Official pricing page notes promotional pricing is available at least through November 21, 2026.",
    "displayName": "GPT-5.6 Sol",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "gpt-5.6-sol",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1220,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Agents",
      "Cyber defense"
    ],
    "sortOrder": 1,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-terra",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1050000,
    "description": "GPT-5.6 Terra balanced model for everyday work at roughly half the cost of GPT-5.5. Generally available as of July 2026.",
    "displayName": "GPT-5.6 Terra",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "gpt-5.6-terra",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1150,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Reasoning",
      "Coding",
      "Cost efficient"
    ],
    "sortOrder": 2,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-luna",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1050000,
    "description": "GPT-5.6 Luna fast and affordable tier for latency-sensitive workloads. Generally available as of July 2026.",
    "displayName": "GPT-5.6 Luna",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "gpt-5.6-luna",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1050,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5",
      "Fast inference",
      "Low cost",
      "Agents"
    ],
    "sortOrder": 3,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.3-codex",
    "catalogVersion": "2026.09.17.1",
    "description": "The most capable agentic coding model to date. Listed in the official Specialized models / Codex pricing group.",
    "displayName": "GPT-5.3 Codex",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "gpt-5.3-codex",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5"
    ],
    "sortOrder": 4,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.5-cyber",
    "catalogVersion": "2026.09.17.1",
    "description": "Cybersecurity model listed in the official Cyber models pricing group (Daybreak program) at $12.50 input / $75.00 output per 1M tokens.",
    "displayName": "GPT-5.5 Cyber",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "gpt-5.5-cyber",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5"
    ],
    "sortOrder": 5,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "openai/gpt-5.6-cyber",
    "catalogVersion": "2026.09.17.1",
    "description": "Our most advanced cybersecurity model for authorized vulnerability research and security testing. Recommended replacement for the deprecating gpt-5.4-cyber (API removal October 1, 2026).",
    "displayName": "GPT-5.6 Cyber",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "gpt-5.6-cyber",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "gpt-5"
    ],
    "sortOrder": 6,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "codex"
    ],
    "supportsTools": true,
    "vendorCode": "openai",
    "vendorName": "OpenAI"
  },
  {
    "catalogKey": "anthropic/claude-fable-5-1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Anthropic top model for demanding reasoning and long-horizon agentic work. 1M-token context, 128K max output. Cache hits priced at 0.025x base input ($0.25 / MTok).",
    "displayName": "Claude Fable 5.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-fable-5-1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1300,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context",
      "Adaptive thinking"
    ],
    "sortOrder": 7,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-mythos-5-1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Limited-availability Claude model for Project Glasswing approved organizations. 1M-token context, 128K max output. Cache hits priced at 0.025x base input ($0.25 / MTok).",
    "displayName": "Claude Mythos 5.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-mythos-5-1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1300,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context",
      "Adaptive thinking"
    ],
    "sortOrder": 8,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Claude flagship for complex agentic coding and enterprise work. 1M-token context, 128K max output. Fast mode (research preview) available at $10 input / $50 output per MTok.",
    "displayName": "Claude Opus 5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-opus-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1230,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context",
      "Thinking"
    ],
    "sortOrder": 9,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-fable-5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Anthropic's most capable widely released model, for the most demanding reasoning and long-horizon agentic work. Public API access restored globally on 2026-07-01 after the June 12 temporary suspension.",
    "displayName": "Claude Fable 5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-fable-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1200,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context",
      "Adaptive thinking"
    ],
    "sortOrder": 10,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-8",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Current Claude Opus frontier model for complex reasoning, coding, and agentic work.",
    "displayName": "Claude Opus 4.8",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-opus-4-8",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1185,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context"
    ],
    "sortOrder": 11,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-7",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Current Claude Opus frontier model for complex reasoning, coding, and agentic work.",
    "displayName": "Claude Opus 4.7",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-opus-4-7",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1170,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Agents",
      "Long context"
    ],
    "sortOrder": 12,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-sonnet-5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Claude Sonnet 5 is Anthropic's most agentic Sonnet model for coding, tool use, and autonomous workflows with introductory API pricing through August 2026.",
    "displayName": "Claude Sonnet 5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-sonnet-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1120,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Agents",
      "Coding",
      "Tool use",
      "Long context"
    ],
    "sortOrder": 13,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-sonnet-4-6",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Claude Sonnet model for reasoning, coding, and agent workflows.",
    "displayName": "Claude Sonnet 4.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 128000,
    "modelId": "claude-sonnet-4-6",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1080,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Reasoning",
      "Coding",
      "Long context",
      "Agents"
    ],
    "sortOrder": 14,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-haiku-4-5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 200000,
    "description": "Fast Claude model for cost-sensitive chat, coding assistance, and agent sub-tasks.",
    "displayName": "Claude Haiku 4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 64000,
    "modelId": "claude-haiku-4-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 980,
    "releaseStage": "active",
    "searchTerms": [
      "claude",
      "Low latency",
      "Cost efficient",
      "Vision",
      "Tool use"
    ],
    "sortOrder": 15,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-5",
    "catalogVersion": "2026.09.17.1",
    "description": "Claude Opus 4.5 (legacy but still available per the official models overview). Listed at $5/$25 per MTok.",
    "displayName": "Claude Opus 4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "claude-opus-4-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "claude"
    ],
    "sortOrder": 16,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-opus-4-6",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Claude Opus 4.6 (legacy but still available per the official models overview). Listed at $5/$25 per MTok with 1M-token context at standard pricing.",
    "displayName": "Claude Opus 4.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "claude-opus-4-6",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "claude"
    ],
    "sortOrder": 17,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "anthropic/claude-sonnet-4-5",
    "catalogVersion": "2026.09.17.1",
    "description": "Claude Sonnet 4.5 (legacy but still available per the official models overview). Listed at $3/$15 per MTok.",
    "displayName": "Claude Sonnet 4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "claude-sonnet-4-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "claude"
    ],
    "sortOrder": 18,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code"
    ],
    "supportsTools": true,
    "vendorCode": "anthropic",
    "vendorName": "Anthropic"
  },
  {
    "catalogKey": "google/gemini-3.8-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Gemini 3.8 Flash current workhorse model building on 3.7 Flash with stronger software engineering and agentic knowledge workflows, customizable thinking levels. GA since 2026-09-02.",
    "displayName": "Gemini 3.8 Flash",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.8-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1110,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Agents",
      "Coding",
      "Multimodal",
      "Long context"
    ],
    "sortOrder": 19,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.7-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Gemini 3.7 Flash workhorse model with improved agentic coding, tool use and long-context knowledge workflows. GA since 2026-08-12.",
    "displayName": "Gemini 3.7 Flash",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.7-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1080,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Agents",
      "Coding",
      "Multimodal",
      "Long context"
    ],
    "sortOrder": 20,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.6-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Gemini 3.6 Flash main-tier model with 17% fewer output tokens than 3.5 Flash, improved agentic coding and multimodal efficiency.",
    "displayName": "Gemini 3.6 Flash",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.6-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1060,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Agents",
      "Coding",
      "Multimodal",
      "Token efficiency"
    ],
    "sortOrder": 21,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.5-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Current Gemini 3.5 Flash main-tier model, GA since May 19, 2026; Gemini 3.6 Flash remains a faster sibling tier, not a replacement.",
    "displayName": "Gemini 3.5 Flash",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.5-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1040,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Agents",
      "Coding",
      "Multimodal",
      "Grounding"
    ],
    "sortOrder": 22,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.5-flash-lite",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Fastest, most cost-efficient Gemini 3.5 Flash Lite for high-throughput agentic search and document processing at 350 tokens/sec.",
    "displayName": "Gemini 3.5 Flash Lite",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.5-flash-lite",
    "outputModalities": [
      "text"
    ],
    "rankScore": 980,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Lowest cost",
      "Low latency",
      "Multimodal",
      "High throughput"
    ],
    "sortOrder": 23,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-flash-lite",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Gemini 3.1 Flash Lite stable model for high-volume low-cost workloads; Gemini 3.5 Flash Lite is a newer sibling, not a replacement.",
    "displayName": "Gemini 3.1 Flash Lite",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.1-flash-lite",
    "outputModalities": [
      "text"
    ],
    "rankScore": 930,
    "releaseStage": "active",
    "searchTerms": [
      "gemini",
      "Low cost",
      "Low latency",
      "Multimodal"
    ],
    "sortOrder": 24,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.8-live",
    "catalogVersion": "2026.09.17.1",
    "description": "默认 Live API 音频到音频模型，用于低延迟语音智能体，2026-09-15 GA。官方同价组：Gemini 3.8 Live / Gemini 3.8 Live Extended Thinking / Gemini 3.1 Flash Live Preview。",
    "displayName": "Gemini 3.8 Live",
    "inputModalities": [
      "text",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "modelId": "gemini-3.8-live",
    "outputModalities": [
      "text",
      "audio"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "gemini"
    ],
    "sortOrder": 25,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.8-live-extended-thinking",
    "catalogVersion": "2026.09.17.1",
    "description": "高推理强度的 Live API 音频到音频模型，支持实时对话中的后台推理，2026-09-15 GA。",
    "displayName": "Gemini 3.8 Live Extended Thinking",
    "inputModalities": [
      "text",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "modelId": "gemini-3.8-live-extended-thinking",
    "outputModalities": [
      "text",
      "audio"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "gemini"
    ],
    "sortOrder": 26,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-pro-preview",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Preview multimodal Gemini model for long-context reasoning.",
    "displayName": "Gemini 3.1 Pro Preview",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "preview",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3.1-pro-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1050,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Long context",
      "Multimodal",
      "Reasoning"
    ],
    "sortOrder": 27,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3-flash-preview",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Fast Gemini 3 preview model for multimodal chat and cost-sensitive reasoning.",
    "displayName": "Gemini 3 Flash Preview",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "preview",
    "maxOutputTokens": 65535,
    "modelId": "gemini-3-flash-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 990,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Low latency",
      "Multimodal",
      "Reasoning",
      "Cost efficient"
    ],
    "sortOrder": 28,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-3.1-flash-live-preview",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 131072,
    "description": "Gemini 3.1 Flash Live preview model for low-latency multimodal realtime sessions.",
    "displayName": "Gemini 3.1 Flash Live Preview",
    "inputModalities": [
      "text",
      "audio",
      "video"
    ],
    "lifecycle": "preview",
    "maxOutputTokens": 8192,
    "modelId": "gemini-3.1-flash-live-preview",
    "outputModalities": [
      "text",
      "audio"
    ],
    "rankScore": 900,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini",
      "Realtime",
      "Audio",
      "Multimodal"
    ],
    "sortOrder": 29,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-robotics-er-2-preview",
    "catalogVersion": "2026.09.17.1",
    "description": "Gemini Robotics Embodied Reasoning 2，面向机器人的视觉语言端点，2026-07-30 公开预览。",
    "displayName": "Gemini Robotics ER 2 Preview",
    "inputModalities": [
      "text",
      "image",
      "video",
      "audio"
    ],
    "lifecycle": "preview",
    "modelId": "gemini-robotics-er-2-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini"
    ],
    "sortOrder": 30,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "google/gemini-robotics-er-2-streaming-preview",
    "catalogVersion": "2026.09.17.1",
    "description": "Gemini Robotics ER 2 的 Live API 实时文本流式端点，2026-07-30 公开预览。",
    "displayName": "Gemini Robotics ER 2 Streaming Preview",
    "inputModalities": [
      "text",
      "image",
      "video",
      "audio"
    ],
    "lifecycle": "preview",
    "modelId": "gemini-robotics-er-2-streaming-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "preview",
    "searchTerms": [
      "gemini"
    ],
    "sortOrder": 31,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "google",
    "vendorName": "Google"
  },
  {
    "catalogKey": "xai/grok-4.6",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 500000,
    "description": "Grok 4.6 flagship model (August 2026) for long-running agents, multi-step coding, and visual work with stronger first-pass reliability.",
    "displayName": "Grok 4.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "grok-4.6",
    "outputModalities": [
      "text"
    ],
    "rankScore": 970,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Code",
      "Reasoning",
      "Agentic tool calling",
      "Long-trajectory reliability"
    ],
    "sortOrder": 32,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-4.5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 500000,
    "description": "Grok 4.5 flagship model for code, agentic tool calling, and configurable reasoning with minimal hallucinations.",
    "displayName": "Grok 4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "grok-4.5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 950,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Code",
      "Reasoning",
      "Agentic tool calling",
      "Vision"
    ],
    "sortOrder": 33,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-4.20-0309-non-reasoning",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Grok 4.20 non-reasoning model optimized for fast general-purpose chat and instruction following.",
    "displayName": "Grok 4.20",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "grok-4.20-0309-non-reasoning",
    "outputModalities": [
      "text"
    ],
    "rankScore": 935,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Chat",
      "Speed",
      "Vision"
    ],
    "sortOrder": 34,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-4.3",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Grok model for general chat, reasoning, and multimodal assistance.",
    "displayName": "Grok 4.3",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "grok-4.3",
    "outputModalities": [
      "text"
    ],
    "rankScore": 930,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Reasoning",
      "Realtime knowledge",
      "Vision"
    ],
    "sortOrder": 35,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "xai/grok-build-0.1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Grok Build lightweight model for fast, cost-efficient inference on simpler tasks.",
    "displayName": "Grok Build 0.1",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "grok-build-0.1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 800,
    "releaseStage": "active",
    "searchTerms": [
      "grok",
      "Speed",
      "Cost efficiency"
    ],
    "sortOrder": 36,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "xai",
    "vendorName": "xAI"
  },
  {
    "catalogKey": "alibaba/qwen3.8-max",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Qwen3.8-Max international flagship reasoning and agent model generally available since August 3, 2026 with 1M context.",
    "displayName": "Qwen3.8 Max",
    "inputModalities": [
      "text",
      "image",
      "video",
      "document"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "qwen3.8-max",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1120,
    "releaseStage": "active",
    "searchTerms": [
      "qwen",
      "Native multimodal",
      "Long context",
      "Agents",
      "Coding"
    ],
    "sortOrder": 37,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "alibaba/qwen3.7-max",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Qwen3.7-Max international flagship reasoning and agent model with 1M context.",
    "displayName": "Qwen3.7 Max",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65530,
    "modelId": "qwen3.7-max",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1060,
    "releaseStage": "active",
    "searchTerms": [
      "qwen",
      "Agents",
      "Coding",
      "Long context",
      "Tool use"
    ],
    "sortOrder": 38,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "alibaba/qwen3.8-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Qwen3.8-Flash open-weight MoE model released on August 26, 2026 with native 1M context and multimodal understanding.",
    "displayName": "Qwen3.8 Flash",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "qwen3.8-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 900,
    "releaseStage": "active",
    "searchTerms": [
      "qwen",
      "Long context",
      "Coding",
      "Chinese"
    ],
    "sortOrder": 39,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "alibaba/qwen3.7-flash",
    "catalogVersion": "2026.09.17.1",
    "description": "QwenCloud 上在售的 Qwen3.7 低延迟档模型，1M 上下文。",
    "displayName": "Qwen3.7 Flash",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "qwen3.7-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "qwen"
    ],
    "sortOrder": 40,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "alibaba/qwen3.7-plus",
    "catalogVersion": "2026.09.17.1",
    "description": "QwenCloud 上在售的 Qwen3.7 均衡档模型，1M 上下文；页面标注限时 20% off。",
    "displayName": "Qwen3.7 Plus",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "qwen3.7-plus",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "qwen"
    ],
    "sortOrder": 41,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "alibaba",
    "vendorName": "Alibaba Cloud"
  },
  {
    "catalogKey": "deepseek/deepseek-v4-pro",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "DeepSeek V4 Pro flagship reasoning and coding model (V4-Pro-0813 GA) with Responses API and Codex support.",
    "displayName": "DeepSeek V4 Pro",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 393216,
    "modelId": "deepseek-v4-pro",
    "outputModalities": [
      "text"
    ],
    "rankScore": 900,
    "releaseStage": "active",
    "searchTerms": [
      "deepseek",
      "Reasoning",
      "Coding",
      "Cost efficient"
    ],
    "sortOrder": 42,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "deepseek",
    "vendorName": "DeepSeek"
  },
  {
    "catalogKey": "deepseek/deepseek-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "DeepSeek-V4.1-Flash, the official model name is deepseek-flash. Current Flash tier; legacy ids deepseek-v4-flash and deepseek-v4-flash-vision-exp are still accepted but their models are retired and now served by this model at Flash pricing. 1M context, 384K max output, Vision, JSON Output, Tool Calls, Responses API and Anthropic API.",
    "displayName": "DeepSeek V4.1 Flash",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 393216,
    "modelId": "deepseek-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 860,
    "releaseStage": "active",
    "searchTerms": [
      "deepseek",
      "Low latency",
      "Cost efficient",
      "Vision understanding",
      "Coding"
    ],
    "sortOrder": 43,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "deepseek",
    "vendorName": "DeepSeek"
  },
  {
    "catalogKey": "moonshot/kimi-k3",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Kimi K3 flagship released on July 16, 2026 at WAIC 2026; 2.8T-parameter Stable LatentMoE with 16-of-896 expert activation, native multimodal vision, and 1M context for long-horizon agent coding.",
    "displayName": "Kimi K3",
    "inputModalities": [
      "text",
      "image",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "kimi-k3",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1090,
    "releaseStage": "active",
    "searchTerms": [
      "kimi",
      "Native multimodal",
      "Long context",
      "Agent coding",
      "Reasoning",
      "Chinese"
    ],
    "sortOrder": 44,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "moonshot",
    "vendorName": "Moonshot Kimi"
  },
  {
    "catalogKey": "moonshot/kimi-k2.6",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Kimi K2.6 model for long-context Chinese, multilingual, and agent workloads.",
    "displayName": "Kimi K2.6",
    "inputModalities": [
      "text",
      "image",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "kimi-k2.6",
    "outputModalities": [
      "text"
    ],
    "rankScore": 875,
    "releaseStage": "active",
    "searchTerms": [
      "kimi",
      "Long context",
      "Chinese",
      "Reasoning",
      "Coding"
    ],
    "sortOrder": 45,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "moonshot",
    "vendorName": "Moonshot Kimi"
  },
  {
    "catalogKey": "zhipu/glm-5.3",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "GLM-5.3 flagship 753B/40B MoE model released on August 18, 2026 with 1M context and 128K output.",
    "displayName": "GLM-5.3",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5.3",
    "outputModalities": [
      "text"
    ],
    "rankScore": 940,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Coding",
      "Agents",
      "Long context",
      "Reasoning"
    ],
    "sortOrder": 46,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5.2",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "GLM-5.2 flagship coding and agent model with 1M context and open-weight lineage.",
    "displayName": "GLM-5.2",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5.2",
    "outputModalities": [
      "text"
    ],
    "rankScore": 920,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Coding",
      "Agents",
      "Long context",
      "Reasoning"
    ],
    "sortOrder": 47,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5.3-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "GLM-5.3-Flash open-weight native multimodal MoE model released on August 26, 2026 with 1M context.",
    "displayName": "GLM-5.3 Flash",
    "inputModalities": [
      "text",
      "image",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5.3-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 880,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Long context",
      "Multimodal",
      "Coding",
      "Chinese"
    ],
    "sortOrder": 48,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5.1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 200000,
    "description": "GLM model for Chinese and multimodal assistance.",
    "displayName": "GLM-5.1",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5.1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 840,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Chinese",
      "Reasoning",
      "Vision"
    ],
    "sortOrder": 49,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 200000,
    "description": "Zhipu GLM-5 text model. Official model overview lists GLM-5 under text models with 200K context and 128K max output, positioned for Agentic long-horizon planning and execution.",
    "displayName": "GLM-5",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Coding",
      "Agents",
      "Long context",
      "Reasoning"
    ],
    "sortOrder": 50,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5-turbo",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 200000,
    "description": "Zhipu GLM-5-Turbo text model. Official model overview lists it with 200K context and 128K max output, tuned for complex long-task execution continuity.",
    "displayName": "GLM-5-Turbo",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5-turbo",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Agents",
      "Long context",
      "Cost efficient"
    ],
    "sortOrder": 51,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-5v-turbo",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 200000,
    "description": "Zhipu GLM-5V-Turbo multimodal coding base model. Official model overview lists it under visual understanding models with 200K context and 128K max output; the official pricing page lists tiered input/output/cache-hit rates below and above 32K input tokens.",
    "displayName": "GLM-5V-Turbo",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "glm-5v-turbo",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "Multimodal",
      "Coding",
      "Visual understanding",
      "Agents"
    ],
    "sortOrder": 52,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "zhipu/glm-ocr",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 32768,
    "description": "Zhipu GLM-OCR lightweight document and image parsing model. Official model overview lists 32K context, single image <= 10 MB, PDF <= 50 MB and up to 100 pages; official pricing lists CNY 0.2 per 1M input and output tokens with cache hits unsupported.",
    "displayName": "GLM-OCR",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "glm-ocr",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "glm",
      "OCR",
      "Document parsing",
      "Image understanding"
    ],
    "sortOrder": 53,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "zhipu",
    "vendorName": "Zhipu AI"
  },
  {
    "catalogKey": "baidu/ernie-5.1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 128000,
    "description": "ERNIE 5.1 flagship model built on the 2.4 trillion parameter ERNIE 5.0 foundation, optimized for Chinese reasoning, knowledge, and search-augmented workloads.",
    "displayName": "ERNIE 5.1",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "ernie-5.1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 880,
    "releaseStage": "active",
    "searchTerms": [
      "ernie",
      "Chinese",
      "Knowledge",
      "Search"
    ],
    "sortOrder": 54,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "baidu",
    "vendorName": "Baidu AI Cloud"
  },
  {
    "catalogKey": "baidu/ernie-4.5-turbo-128k",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 128000,
    "description": "ERNIE 4.5 Turbo high-performance model optimized for multi-turn long-history dialogue and long-document understanding.",
    "displayName": "ERNIE 4.5 Turbo",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 12288,
    "modelId": "ernie-4.5-turbo-128k",
    "outputModalities": [
      "text"
    ],
    "rankScore": 850,
    "releaseStage": "active",
    "searchTerms": [
      "ernie",
      "Long context",
      "Chinese",
      "Multi-turn dialogue"
    ],
    "sortOrder": 55,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "baidu",
    "vendorName": "Baidu AI Cloud"
  },
  {
    "catalogKey": "baidu/ernie-5.0",
    "catalogVersion": "2026.09.17.1",
    "description": "文心 5.0 原生全模态旗舰大模型（非思考基础版），128k 上下文、最大输出 65536 tokens。",
    "displayName": "ERNIE 5.0",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "modelId": "ernie-5.0",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "ernie"
    ],
    "sortOrder": 56,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "baidu",
    "vendorName": "Baidu"
  },
  {
    "catalogKey": "baidu/ernie-5.0-thinking-preview",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 128000,
    "description": "ERNIE thinking preview model for Chinese reasoning workloads.",
    "displayName": "ERNIE 5.0 Thinking Preview",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "preview",
    "maxOutputTokens": 65536,
    "modelId": "ernie-5.0-thinking-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 820,
    "releaseStage": "preview",
    "searchTerms": [
      "ernie",
      "Chinese",
      "Reasoning",
      "Vision"
    ],
    "sortOrder": 57,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "baidu",
    "vendorName": "Baidu AI Cloud"
  },
  {
    "catalogKey": "tencent/hy4-preview",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1000000,
    "description": "Tencent Hunyuan Hy4 preview model released on August 28, 2026 with 770B-parameter MoE (49B activated) and 1M context.",
    "displayName": "Hy4 Preview",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "hy4-preview",
    "outputModalities": [
      "text"
    ],
    "rankScore": 905,
    "releaseStage": "preview",
    "searchTerms": [
      "hunyuan",
      "Reasoning",
      "Code",
      "Agent",
      "Long context"
    ],
    "sortOrder": 58,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy3",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Tencent Hy3 fast/slow thinking fusion model with MoE architecture (295B total params, 21B activated). Supports 256K context. Successor to Hunyuan 2.0 with significant improvements in complex reasoning, instruction following, context learning, code generation, and agent capabilities.",
    "displayName": "Hy3",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "hy3",
    "outputModalities": [
      "text"
    ],
    "rankScore": 900,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Reasoning",
      "Code",
      "Agent",
      "Long context",
      "Instruction following"
    ],
    "sortOrder": 59,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy-mt2-lite",
    "catalogVersion": "2026.09.17.1",
    "description": "Tencent Hunyuan Hy-MT2-Lite translation model listed on the official TokenHub model price page at CNY 0.3 per 1M input tokens and CNY 1.2 per 1M output tokens. Context window is not stated on the official price page.",
    "displayName": "Hy-MT2-Lite",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "hy-mt2-lite",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Translation",
      "Multilingual",
      "Cost efficient"
    ],
    "sortOrder": 60,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy-mt2-plus",
    "catalogVersion": "2026.09.17.1",
    "description": "Tencent Hunyuan Hy-MT2-Plus translation model listed on the official TokenHub model price page at CNY 0.5 per 1M input tokens and CNY 2 per 1M output tokens. Context window is not stated on the official price page.",
    "displayName": "Hy-MT2-Plus",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "hy-mt2-plus",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Translation",
      "Multilingual"
    ],
    "sortOrder": 61,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy-mt2-pro",
    "catalogVersion": "2026.09.17.1",
    "description": "Tencent Hunyuan Hy-MT2-Pro translation model listed on the official TokenHub model price page at CNY 0.5 per 1M input tokens and CNY 2 per 1M output tokens. Context window is not stated on the official price page.",
    "displayName": "Hy-MT2-Pro",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "hy-mt2-pro",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Translation",
      "Multilingual"
    ],
    "sortOrder": 62,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy-role",
    "catalogVersion": "2026.09.17.1",
    "description": "Tencent Hunyuan Hy-Role role-play dialogue model listed on the official TokenHub model price page at CNY 2.4 per 1M input tokens and CNY 9.6 per 1M output tokens. Context window is not stated on the official price page.",
    "displayName": "Hy-Role",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "hy-role",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Role play",
      "Dialogue",
      "Chinese"
    ],
    "sortOrder": 63,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "tencent/hy-role-latest",
    "catalogVersion": "2026.09.17.1",
    "description": "Tencent Hunyuan Hy-Role-Latest role-play dialogue model listed on the official TokenHub model price page at CNY 2.4 per 1M input tokens and CNY 9.6 per 1M output tokens. Context window is not stated on the official price page.",
    "displayName": "Hy-Role-Latest",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "modelId": "hy-role-latest",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "hunyuan",
      "Role play",
      "Dialogue",
      "Chinese"
    ],
    "sortOrder": 64,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "tencent",
    "vendorName": "Tencent Cloud"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-1-pro-260628",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Doubao Seed 2.1 Pro deep-thinking flagship for complex coding, long-horizon agents, and multimodal understanding.",
    "displayName": "Doubao Seed 2.1 Pro",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "doubao-seed-2-1-pro-260628",
    "outputModalities": [
      "text"
    ],
    "rankScore": 930,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Coding",
      "Agents",
      "Reasoning",
      "Multimodal"
    ],
    "sortOrder": 65,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-1-turbo-260628",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Doubao Seed 2.1 Turbo deep-thinking model for high-throughput coding and agent workloads at lower latency and cost.",
    "displayName": "Doubao Seed 2.1 Turbo",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "doubao-seed-2-1-turbo-260628",
    "outputModalities": [
      "text"
    ],
    "rankScore": 910,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Coding",
      "Agents",
      "Throughput",
      "Cost"
    ],
    "sortOrder": 66,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-lite-260215",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Seed 2.0 Lite balances output quality and response speed. Ideal as a general-purpose, production-grade model with omni-modal understanding.",
    "displayName": "Doubao Seed 2.0 Lite",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "doubao-seed-2-0-lite-260215",
    "outputModalities": [
      "text"
    ],
    "rankScore": 880,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Multimodal",
      "Speed",
      "Agent",
      "Coding"
    ],
    "sortOrder": 67,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-code-preview-260215",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Doubao Seed 2.0 Code model optimized for software engineering, debugging, and agentic coding workflows.",
    "displayName": "Doubao Seed 2.0 Code",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "doubao-seed-2-0-code-preview-260215",
    "outputModalities": [
      "text"
    ],
    "rankScore": 870,
    "releaseStage": "preview",
    "searchTerms": [
      "doubao-seed",
      "Coding",
      "Agents",
      "Chinese",
      "Multimodal"
    ],
    "sortOrder": 68,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-pro-260215",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Doubao Seed 2.0 Pro model for Chinese multimodal assistance.",
    "displayName": "Doubao Seed 2.0 Pro",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "doubao-seed-2-0-pro-260215",
    "outputModalities": [
      "text"
    ],
    "rankScore": 850,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Chinese",
      "Multimodal",
      "Enterprise"
    ],
    "sortOrder": 69,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-mini-260215",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 128000,
    "description": "Seed 2.0 Mini is optimized for inference throughput and deployment density. Designed for high concurrency and batch generation scenarios.",
    "displayName": "Doubao Seed 2.0 Mini",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 16384,
    "modelId": "doubao-seed-2-0-mini-260215",
    "outputModalities": [
      "text"
    ],
    "rankScore": 830,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Speed",
      "Cost efficiency",
      "High concurrency"
    ],
    "sortOrder": 70,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/dola-seed-2-1-turbo-260628",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Dola (Doubao) Seed 2.1 Turbo on BytePlus ModelArk. 256K context window, 256K max input, 256K max output including CoT.",
    "displayName": "Dola Seed 2.1 Turbo",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 262144,
    "modelId": "dola-seed-2-1-turbo-260628",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "dola-seed",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 71,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-lite-260428",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Doubao Seed 2.0 Lite 260428 revision, listed under 往期模型 on the Volcengine Ark model list. 256K context window, 224K max input, 128K max answer and 128K max CoT.",
    "displayName": "Doubao Seed 2.0 Lite (260428)",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "doubao-seed-2-0-lite-260428",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Multimodal understanding",
      "Deep thinking",
      "GUI tasks",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 72,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-0-mini-260428",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Doubao Seed 2.0 Mini 260428 revision, listed under 往期模型 on the Volcengine Ark model list. 256K context window, 224K max input, 128K max answer and 128K max CoT.",
    "displayName": "Doubao Seed 2.0 Mini (260428)",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "doubao-seed-2-0-mini-260428",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Multimodal understanding",
      "Deep thinking",
      "GUI tasks",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 73,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-2-1-pro-260915",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Doubao Seed 2.1 Pro 260915 revision on Volcengine Ark: 1024K context window, 1024K max input, 256K max answer and 256K max CoT. Listed under 推荐模型 alongside the 260628 revision.",
    "displayName": "Doubao Seed 2.1 Pro (260915)",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 262144,
    "modelId": "doubao-seed-2-1-pro-260915",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Deep thinking",
      "Multimodal understanding",
      "GUI tasks",
      "Tool use",
      "Long context"
    ],
    "sortOrder": 74,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/doubao-seed-evolving",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Doubao Seed 快速迭代模型, listed first under 推荐模型 on the Volcengine Ark model list (2026-09-16 revision). 1024K context window, 1024K max input, 256K max answer and 256K max CoT.",
    "displayName": "Doubao Seed Evolving",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 262144,
    "modelId": "doubao-seed-evolving",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "doubao-seed",
      "Fast iteration",
      "Deep thinking",
      "Multimodal understanding",
      "GUI tasks",
      "Tool use"
    ],
    "sortOrder": 75,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-code-preview-260328",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Code Preview 260328 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Code Preview",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-code-preview-260328",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "preview",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 76,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-lite-260228",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Lite 260228 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Lite (260228)",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-lite-260228",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 77,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-lite-260428",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Lite 260428 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Lite (260428)",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-lite-260428",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 78,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-mini-260215",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Mini 260215 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Mini (260215)",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-mini-260215",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 79,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-mini-260428",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Mini 260428 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Mini (260428)",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-mini-260428",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 80,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "bytedance/seed-2-0-pro-260328",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 262144,
    "description": "Seed 2.0 Pro 260328 on BytePlus ModelArk. 256K context window, 128K max output including CoT.",
    "displayName": "Dola Seed 2.0 Pro",
    "inputModalities": [
      "text",
      "image"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "seed-2-0-pro-260328",
    "outputModalities": [
      "text"
    ],
    "rankScore": 0,
    "releaseStage": "active",
    "searchTerms": [
      "seed-2-0",
      "Deep reasoning",
      "Text generation",
      "Multi-modal understanding",
      "Tool use",
      "Structured output"
    ],
    "sortOrder": 81,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "bytedance",
    "vendorName": "ByteDance"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.7",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.7 text model for long-context coding, office, agent and tool workflows.",
    "displayName": "MiniMax M2.7",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.7",
    "outputModalities": [
      "text"
    ],
    "rankScore": 805,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Code",
      "Tools",
      "Long context"
    ],
    "sortOrder": 82,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.7-highspeed",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.7 high-speed variant with the same model quality and lower latency.",
    "displayName": "MiniMax M2.7 Highspeed",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.7-highspeed",
    "outputModalities": [
      "text"
    ],
    "rankScore": 795,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Low latency",
      "Code",
      "Tools"
    ],
    "sortOrder": 83,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-H3-Context-IR",
    "catalogVersion": "2026.09.17.1",
    "description": "MiniMax-H3-Context-IR deeply understands multimodal context and produces structured, semantically richer video prompts; billed per token.",
    "displayName": "MiniMax H3 Context IR",
    "inputModalities": [
      "text",
      "image",
      "video",
      "audio"
    ],
    "lifecycle": "active",
    "modelId": "MiniMax-H3-Context-IR",
    "outputModalities": [
      "text"
    ],
    "rankScore": 780,
    "releaseStage": "active",
    "searchTerms": [
      "minimax-video",
      "Multimodal context understanding",
      "Video prompt generation"
    ],
    "sortOrder": 84,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.5 text model optimized for coding, tool use, search and office productivity.",
    "displayName": "MiniMax M2.5",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 780,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Code",
      "Tools",
      "Value"
    ],
    "sortOrder": 85,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.1",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.1 text model, listed by the official docs as a legacy model that is still served.",
    "displayName": "MiniMax M2.1",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.1",
    "outputModalities": [
      "text"
    ],
    "rankScore": 775,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Code",
      "Tools",
      "Long context"
    ],
    "sortOrder": 86,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.5-highspeed",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.5 high-speed variant with the same model quality and faster inference.",
    "displayName": "MiniMax M2.5 Highspeed",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.5-highspeed",
    "outputModalities": [
      "text"
    ],
    "rankScore": 770,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Low latency",
      "Code",
      "Value"
    ],
    "sortOrder": 87,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2.1-highspeed",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2.1-Highspeed text model, listed by the official docs as a legacy model that is still served.",
    "displayName": "MiniMax M2.1-Highspeed",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 32768,
    "modelId": "MiniMax-M2.1-highspeed",
    "outputModalities": [
      "text"
    ],
    "rankScore": 765,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Low latency",
      "Code",
      "Value"
    ],
    "sortOrder": 88,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/MiniMax-M2",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 204800,
    "description": "MiniMax M2 text model, listed by the official docs as a legacy model that is still served.",
    "displayName": "MiniMax M2",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "MiniMax-M2",
    "outputModalities": [
      "text"
    ],
    "rankScore": 755,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Code",
      "Tools",
      "Long context"
    ],
    "sortOrder": 89,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "minimax/M2-her",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 65536,
    "description": "MiniMax M2-her text chat model for role-playing and long-horizon multi-turn dialogue.",
    "displayName": "MiniMax M2-her",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 2048,
    "modelId": "M2-her",
    "outputModalities": [
      "text"
    ],
    "rankScore": 735,
    "releaseStage": "active",
    "searchTerms": [
      "minimax",
      "Role play",
      "Dialogue",
      "Character customization"
    ],
    "sortOrder": 90,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": false,
    "vendorCode": "minimax",
    "vendorName": "MiniMax"
  },
  {
    "catalogKey": "stepfun/step-3.7-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "StepFun flagship multimodal reasoning model with native image and video understanding.",
    "displayName": "Step 3.7 Flash",
    "inputModalities": [
      "text",
      "image",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "step-3.7-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 960,
    "releaseStage": "active",
    "searchTerms": [
      "step-flash",
      "Multimodal",
      "Agents",
      "Coding",
      "Reasoning"
    ],
    "sortOrder": 91,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "stepfun",
    "vendorName": "StepFun"
  },
  {
    "catalogKey": "stepfun/step-3.5-flash-2603",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "Agent-optimized Step 3.5 Flash variant with faster inference and reasoning_effort controls.",
    "displayName": "Step 3.5 Flash 2603",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "step-3.5-flash-2603",
    "outputModalities": [
      "text"
    ],
    "rankScore": 920,
    "releaseStage": "active",
    "searchTerms": [
      "step-flash",
      "Agents",
      "Coding",
      "Efficiency",
      "Tools"
    ],
    "sortOrder": 92,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "stepfun",
    "vendorName": "StepFun"
  },
  {
    "catalogKey": "stepfun/step-3.5-flash",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 256000,
    "description": "StepFun flagship sparse MoE reasoning model for agents, coding, and tool use.",
    "displayName": "Step 3.5 Flash",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 65536,
    "modelId": "step-3.5-flash",
    "outputModalities": [
      "text"
    ],
    "rankScore": 900,
    "releaseStage": "active",
    "searchTerms": [
      "step-flash",
      "Agents",
      "Coding",
      "Reasoning",
      "Tools"
    ],
    "sortOrder": 93,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "stepfun",
    "vendorName": "StepFun"
  },
  {
    "catalogKey": "meituan/longcat-2.0",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Meituan LongCat 2.0 trillion-parameter MoE agentic model for coding, agent workflows, and ultra-long context tasks. Open-sourced under MIT license with 1M token context window.",
    "displayName": "LongCat 2.0",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "longcat-2.0",
    "outputModalities": [
      "text"
    ],
    "rankScore": 920,
    "releaseStage": "active",
    "searchTerms": [
      "longcat",
      "Chinese",
      "Coding",
      "Agentic",
      "Long context"
    ],
    "sortOrder": 94,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [],
    "supportsTools": true,
    "vendorCode": "meituan",
    "vendorName": "Meituan"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5-pro",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Xiaomi MiMo V2.5 Pro - 1T parameter MoE model with 42B active parameters, optimized for agentic and long-horizon tasks.",
    "displayName": "MiMo V2.5 Pro",
    "inputModalities": [
      "text"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "mimo-v2.5-pro",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1100,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Reasoning",
      "Coding",
      "Agents",
      "Long Context"
    ],
    "sortOrder": 95,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  },
  {
    "catalogKey": "xiaomi/mimo-v2.5",
    "catalogVersion": "2026.09.17.1",
    "contextTokens": 1048576,
    "description": "Xiaomi MiMo V2.5 - Native omnimodal model supporting text, image, video, and audio understanding with 310B total / 15B active parameters.",
    "displayName": "MiMo V2.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "lifecycle": "active",
    "maxOutputTokens": 131072,
    "modelId": "mimo-v2.5",
    "outputModalities": [
      "text"
    ],
    "rankScore": 1050,
    "releaseStage": "active",
    "searchTerms": [
      "mimo-v2.5",
      "Multimodal",
      "Reasoning",
      "Coding",
      "Agents",
      "Long Context"
    ],
    "sortOrder": 96,
    "sourceObservedAt": "2026-09-17T00:00:00Z",
    "supportedProviderIds": [
      "claude-code",
      "codex",
      "gemini"
    ],
    "supportsTools": true,
    "vendorCode": "xiaomi",
    "vendorName": "Xiaomi MiMo"
  }
];
