#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate a report of catalog prices that the runtime cannot select.

These entries are structurally valid (schema + migrator stable) but their
discriminator dimension is not populated by the runtime, so the rate is
unreachable: the meter resolves no price and the request fails (or falls back
across regions). Each row carries a suggested remediation; none is applied
automatically because collapsing/merging prices is a product decision.

Usage:
    python tools/report-unreachable-pricing.py            # rewrite the report
    python tools/report-unreachable-pricing.py --check    # fail if it drifted

The report is a generated artifact: it went stale once (47 rows committed while
the catalog already carried 472), so --check lets a caller detect that drift
instead of trusting a hand-committed file.
"""
import json, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS = os.path.join(ROOT, "models")

RUNTIME_DIMS = {
    "api_code", "operation_id", "tier_code", "quality", "resolution",
    "duration_seconds", "result_count", "media_type", "input_type", "output_type",
    "context_tokens", "vendor_code", "provider_code", "region_code", "catalog_key",
    "model", "meter_code", "product_code", "operation_code", "occurred_at",
}

def dim_label(dim):
    return {
        "tier_code": "request body tier (/tier_code,/service_tier,/tier) - chat never sends it",
        "media_direction": "not populated by the runtime at all",
    }.get(dim, f"not populated by the runtime ({dim})")

rows = []
for path in sorted(glob.glob(os.path.join(MODELS, "*", "*", "pricing", "*.json"))):
    try:
        pricing = json.load(open(path, encoding="utf-8"))
    except Exception:
        continue
    for p in pricing.get("prices", []):
        for c in p.get("conditions", []):
            dim = c.get("dimensionCode")
            if dim == "tier_code" and p.get("rateVariant") != "time_window":
                pass  # dead tier_code on a standard rate -> report
            elif dim in RUNTIME_DIMS:
                continue
            tier = next((cc.get("value") for cc in p.get("conditions", [])
                         if cc.get("dimensionCode") == "tier_code"), None)
            rows.append({
                "file": os.path.relpath(path, MODELS).replace(os.sep, "/"),
                "priceId": p.get("priceId"),
                "meter": p.get("meterCode"),
                "unitPrice": p.get("unitPrice"),
                "currency": p.get("currency") or pricing.get("currency"),
                "unitSize": p.get("unitSize"),
                "dimension": dim,
                "dimensionNote": dim_label(dim),
                "tierValue": tier,
                "thresholdTokens": p.get("thresholdTokens"),
            })

rows.sort(key=lambda r: (r["file"], r["priceId"]))
out = ["# Unreachable catalog prices (runtime dimension gaps)\n",
       "Generated by tools/report-unreachable-pricing.py. Structurally valid rates",
       "whose discriminator dimension the runtime never populates -> the meter",
       "resolves no price at runtime. Fixing requires either a runtime dimension",
       "or merging tiers - a product decision, so nothing here is auto-applied.\n",
       "| file | priceId | meter | price | currency | unitSize | dimension | tier | thresholdTokens |",
       "|---|---|---|---|---|---|---|---|---|"]
for r in rows:
    out.append(f"| {r['file']} | {r['priceId']} | {r['meter']} | {r['unitPrice']} | "
               f"{r['currency']} | {r['unitSize']} | {r['dimension']} | {r['tierValue'] or '-'} | "
               f"{r['thresholdTokens'] or '-'} |")

DOC_PATH = os.path.join(ROOT, "docs", "pricing-unreachable-rates.md")
next_text = "\n".join(out) + "\n"

if "--check" in sys.argv:
    current = None
    if os.path.isfile(DOC_PATH):
        with open(DOC_PATH, encoding="utf-8") as fh:
            current = fh.read()
    if current != next_text:
        print("drift docs/pricing-unreachable-rates.md")
        print(f"  committed: {0 if current is None else current.count(chr(10))} line(s)")
        print(f"  expected : {next_text.count(chr(10))} line(s) from {len(rows)} unreachable rate(s)")
        sys.exit(1)
    print(f"docs/pricing-unreachable-rates.md is current ({len(rows)} row(s))")
    sys.exit(0)

# newline="\n" pins LF: the default text-mode write translates "\n" to
# os.linesep, so on Windows this generated artifact would come out CRLF and
# every regeneration would show up as a whole-file diff against the LF
# convention the repo commits. The read side keeps default newline handling so
# the --check comparison tolerates a CRLF working tree.
with open(DOC_PATH, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(next_text)
print(f"wrote docs/pricing-unreachable-rates.md with {len(rows)} rows")
